### ISSUE TITLE
question: does this also close associated loclist/qf?

### ISSUE THREAD

**Issue by davidosomething** [mhinz/vim-sayonara#1]
The loclist associated with a buffer typically stays open when `:bd` in vim
Does this handle that?

**Comment by mhinz** [comment]
Good idea, I'll implement that. :+1:

_Note_: I uploaded the plugin yesterday and there are still some bugs on my list, so don't be discouraged if you encounter some. I'll put quite some work into it this week.

Thanks for the early feedback!

**Comment by mhinz** [comment]
I dropped command arguments to keep the plugin simple enough.

Now, everytime a window gets closed, its associated location window is closed, too. (Location lists are never associated with a buffer.)

**Comment by davidosomething** [comment]
there's still one case where you get a stay loclist:
- open a file with loclist open
- `:vs` -- you will be in a new split with the same file)
- `:bd` -- the file will be completely unloaded, but the loclist will still be open with an empty buffer

**Comment by mhinz** [comment]
Unfortunately there's no good way to solve this. Since there's no association between buffers and windows, one can never tell if there's a location list.
- open `file1` with loclist open (window 1 has a loclist)
- switch to another buffer with `file2` (window 1 still has a loclist)
- create new window and switch to `file1` (window 1 still has a loclist, window 2 hasn't)

Now what should happen if you close window 2?

It would be easy to find all the windows that also contain the current buffer, but you never know why the location list was shown in the first place. You could close it in all windows that show the current buffer, but then this might be wrong, since another buffer needs that location list.

Or even easier: 2 windows could have different location lists but show the same buffer.

**Comment by mhinz** [comment]
Since it's more of a Vim design issue, I'll close this now.
