### ISSUE TITLE
Request: Is it possible to map :q! to :Sayonara without saving?

### ISSUE THREAD

**Issue by wintermelons** [mhinz/vim-sayonara#12]
Vim noob here, learnt that I've been using Tabs wrong hours ago, and I'm trying to switch to buffers. I currently have this in my `.vimrc`, which works very well:

```
cnoreabbrev wq w<bar>Sayonara
cnoreabbrev q Sayonara
```

But how would I preserve `:q!` function call `:Sayonara` and not save at the same time? Is there a possible remap possible? Currently it just calls `:Sayonara!`, whereas I'm looking for a setup similar to tabs where I still wish to close the window if there are no more tabs (buffers). 

Thanks in advance!

**Comment by mhinz** [comment]
I see the problem, but there's no way to solve that with cmaps. I get that you want to silently replace the standard `:q` without affecting `:q!`, but I can't come up with a good way to do that.

Even though abbreviating `q!` alone works; abbreviating `q` and `q!` won't work, because `!` is a non-word character that will trigger the `q` abbreviation. Therefore `q!` becomes a shadowed abbreviation that is impossible to execute.

In case you don't know about it: in normal mode, `ZQ` will act as `:q!`. See `:h ZQ`.

Personally I'd use an own mapping for it, like:

```vim
nnoremap <space>q :Sayonara<cr>
nnoremap <space>Q :Sayonara!<cr>
```

Or maybe..

```
command! -bang Q Sayonara<bang>
```

Then you can use `:Q` for `:Sayonara` and `:Q!` for `:Sayonara!`.

HTH

**Comment by MasterMedo** [comment]
Isn't this counter intuitive compared to what bang usually means in this context?
I'd expect `:Sayonara!` to map to `:q!` or `:bd!` based on the context.

I can see that the current behaviour of both `:Sayonara` and `:Sayonara!` is useful, but I  do `:q!` and `bd!` just as often (instead of undoing the changes, holding `u`, and then quitting), if you provided that option as e.g. `Sayonara!!` one could do:

```vim
  cnoreabbrev <expr>  q   v:char =~ "!" ? "q" : "Sayonara"
  cnoreabbrev <expr>  wq  v:char =~ "!" ? "wq" : "w<bar>Sayonara"
  cnoreabbrev         wq! w<bar>Sayonara!!
  cnoreabbrev         q!  Sayonara!!
```

EDIT:
When typing `:Sayonara` with unsaved changes a prompt comes up asking to choose an option, is it possible to somehow pass a `char` to `getchar()` when calling a command, or can you make it so one can pass one more argument to the function, not just the `<bang>`, something like `exec 'Sayonara' 's'`?
