### ISSUE TITLE
Scratch buffer

### ISSUE THREAD

**Issue by onemanstartup** [mhinz/vim-sayonara#4]
When I have 3 opened windows and 2 buffers
Then I am trying calling :Sayonara! in one window
I get cycling between 2 buffers.
It will be cool if :Sayonara! created scratch buffer in third window as last action.

**Comment by mhinz** [comment]
Well, I admit that's it might seem strange at first, but it's by design. :-)

Opposed to all other plugins that handle buffers, this plugin never deletes buffers that are shown in other windows. (Let me stress this: other plugins might close other windows than the current one, which is rude.) So you have to keep all windows (and maybe multiple tabpages) in mind. But when you use `:Sayonara!`, it will only affect the current window. Always. Thus less braincycles are needed!

Example: 3 windows, 2 buffers, therefore one buffer is shown in two windows.

Now if you use `:Sayonara!` on the window showing the "unique" buffer, it will get deleted and you have 3 windows all showing the same last buffer. Just what one would expect.

You describe the case, where you use `:Sayaona!` on one of the two windows showing the same buffer. The buffer won't deleted (since it's also shown in another window) and the window switches to the only other active buffer. Now _that_ buffer is shown twice. Another `:Sayonara!` will cycle back to the first buffer and so on.

You have a similar effect if you open a single file in one window, split the window via `<c-w>s`, and then use `:Sayonara!` a few times. It can't delete the only active buffer (since it's once again shown in the other window).

As far as I see it, there's no other way to handle this, without handling it as a corner case, which I'd like to avoid due to consistency purposes.
